version: '3.3'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - test_mysql.env
        ports:
            - '3306:3306'
    notebook:
        image: aguinaldoabbj/alpine-jupyter
        hostname: notebook
        ports:
            - "8888:8888"
        volumes: 
            - $HOME:/notebooks
        environment:
            user: root
        env_file:
            - test_mysql.env
