version: '3.3'

services:
    mysqldb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - test_mysql.env
        ports:
            - '3306:3306'
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 100M
                reservations:
                    cpus: '0.25'
                    memory: 20M
    notebook:
        image: aguinaldoabbj/alpine-jupyter
        hostname: notebook
        ports:
            - "8888:8888"
        volumes: 
            - $HOME:/notebooks
        environment:
            user: root
        env_file:
            - test_mysql.env
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G
                reservations:
                    cpus: '0.25'
                    memory: 50M
