FROM alpine

COPY motd /etc/motd

#no-cache switch updates package index and deletes cache
RUN apk --no-cache add \
    bash \
    tini
    
ENTRYPOINT ["/tini", "--"]

CMD ["bash"]

#CMD ["tail -f", "/dev/null"]
