FROM alpine

# some customization
COPY motd /etc/
RUN echo '[ ! -z "$TERM" -a -r /etc/motd ] && cat /etc/motd && head -1 /etc/issue' >> /root/.bashrc

# no-cache switch updates package index and deletes cache
RUN apk --no-cache add \
    bash \
    tini
    
# safe entry   
ENTRYPOINT ["sbin/tini", "--"]

# makes container run forever
#CMD ["/bin/tail", "-f", "/dev/null"]
CMD tail -f /dev/null